=== VijayEluri/planets-suite/ptb/trunk/application/src/main/resources/eu/planets_project/tb/impl/BenchmarkGoalsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="BenchmarkGoals" type="BenchmarkGoalsType">
		 <xs:unique name="itemID">
			<xs:selector xpath="./category/item"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
	
	<xs:complexType name="BenchmarkGoalsType">
			<xs:sequence>
				 <xs:element name="category" type="CategoryType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>

	
	<xs:complexType name="CategoryType">
			<xs:sequence>
				 <xs:element name="item" type="ItemType" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	
	<xs:complexType name="ItemType">
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1"/>
				<xs:element name="definition" type="xs:string" minOccurs="1"/>
				<xs:element name="description" type="xs:string" minOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="type" type="javaTypes" use="required"/>
			<xs:attribute name="scale" type="xs:string" use="required"/>
			<xs:attribute name="version" type="xs:string" use="required"/>
		</xs:complexType>

	<xs:simpleType name="javaTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="java.lang.String"/>
			<xs:enumeration value="java.lang.Boolean"/>
			<xs:enumeration value="java.lang.Integer"/>
			<xs:enumeration value="lava.lang.Long"/>
			<xs:enumeration value="java.lang.Float"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== VijayEluri/planets-suite/webaap-testbed/src/main/resources/eu/planets_project/tb/impl/BenchmarkGoals.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Kantoorautomatisering (Nationaal Archief) -->
<BenchmarkGoals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BenchmarkGoalsSchema.xsd">
	<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="BenchmarkGoalsSchema.xsd" -->
	<category name="Text">
		<item id="text-gen1" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of levels</name>
			<definition>Defines the number of subdivision levels beneath the highest level in a text.</definition>
			<description>If the text is e.g. divided in parts, which each have chapters, which are divided in paragraphs, the number of levels would be 3. For most emails, the number of levels will be 0 if they are not subdivided. Makes it possible to decide whether the structure has been preserved / characterised. "structure"</description>
		</item>
		<item id="text-gen2" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of level 1 subdivisions</name>
			<definition>Identifies the number of highest level parts the text is divided in.</definition>
			<description>IIf the text has a table of contents, a preface and 3 chapters, this number could be 5. Makes it possible to decide whether the structure has been preserved / characterised, and e.g. no chapters have been lost. "structure"</description>
		</item>
		<item id="text-gen3" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of footnotes</name>
			<definition>Indicates the number of footnotes in the text.</definition>
			<description>Count the number of footnotes in the entire text. "structure"</description>
		</item>
		<item id="text-gen4" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of footnote references (indicators).</name>
			<definition>Indicates the number of footnote references (indicators).</definition>
			<description>Count the number of footnote references (indicators) in the entire text. "structure"</description>
		</item>
		<item id="text-gen5" type="java.lang.Boolean" scale="yes/no" version="1.0">
			<name>Use of headers</name>
			<definition>Indicates whether or not headers are used in the text.</definition>
			<description>Yes if (one or more) headers are used, no if not. "structure"</description>
		</item>
		<item id="text-gen6" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of different headers</name>
			<definition>Indicates the number of different headers used in the text.</definition>
			<description>Count the number of different headers, e.g. each chapter could have a different header. "structure"</description>
		</item>
		<item id="text-gen7" type="java.lang.Boolean" scale="yes/no" version="1.0">
			<name>Use of footers</name>
			<definition>Indicates whether or not footers are used in the text.</definition>
			<description>Yes if (one or more) footers are used, no if not. "structure"</description>
		</item>
		<item id="text-gen8" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of different footers</name>
			<definition>Indicates the number of different footers used in the text.</definition>
			<description>Count the number of different footers e.g. each chapter could have a different footer. "structure"</description>
		</item>
		<item id="text-gen9" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of tables</name>
			<definition>Indicates the number of tables used in the text.</definition>
			<description>Count the number of tables. "structure"</description>
		</item>
		<item id="text-gen10" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of table captions</name>
			<definition>Indicates the number of table captions.</definition>
			<description>Count the number of table captions. "structure"</description>
		</item>
		<item id="text-gen11" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of images</name>
			<definition>Indicates the number of image captions used in the text.</definition>
			<description>Count the number of image captions. "structure"</description>
		</item>
		<item id="text-gen12" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of image captions</name>
			<definition>Indicates the number of images used in the text.</definition>
			<description>Count the number of images. "structure"</description>
		</item>
		<item id="text-gen13" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of graphics</name>
			<definition>Indicates the number of graphics used in the text.</definition>
			<description>Count the number of graphics. "structure"</description>
		</item>
		<item id="text-gen14" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of graphics captions</name>
			<definition>Indicates the number of graphic captions used in the text.</definition>
			<description>Count the number of graphic captions. "structure"</description>
		</item>
		<item id="text-gen15" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of formulas</name>
			<definition>Indicates the number of formulas used in the text.</definition>
			<description>Count the number of formulas. "structure"</description>
		</item>
		<item id="text-gen16" type="java.lang.Boolean" scale="yes/no" version="1.0">
			<name>Use of signatures</name>
			<definition>Indicates whether or not the text contains signatures.</definition>
			<description>Yes if text contains one ore more signatures, no otherwise. "structure"</description>
		</item>
		<item id="text-gen17" type="java.lang.Boolean" scale="yes/no" version="1.0">
			<name>Use of signatures</name>
			<definition>Indicates whether or not the text contains any signatures.</definition>
			<description>Yes if text contains one ore more signatures, no otherwise. Can be in any form, e.g. digital signature ir watermark-like. "structure"</description>
		</item>
		<item id="text-gen18" type="java.lang.Boolean" scale="yes/no" version="1.0">
			<name>Use of watermarks / background images</name>
			<definition>Indicates whether or not the text contains a watermark or background image.</definition>
			<description>Yes if text contains (one ore more) watermarks or background images.  "structure"</description>
		</item>
		<item id="text-gen19" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of working hyperlinks</name>
			<definition>Indicates the number of working hyperlinks used in the text.</definition>
			<description>Count the number of working hyperlinks. "behaviour"</description>
		</item>
		<item id="text-gen20" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of pages</name>
			<definition>Defines the number of pages.</definition>
			<description>Count the number of pages, including the front page. "appearance"</description>
		</item>
		<item id="text-gen21" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of lines</name>
			<definition>Defines the number of lines.</definition>
			<description>Count the number of lines.  "appearance"</description>
		</item>
		<item id="text-gen22" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of characters</name>
			<definition>Defines the number of characters.</definition>
			<description>Count the number of characters. "appearance"</description>
		</item>
		<item id="text-page1" type="java.lang.Float" scale="cm. / inch." version="1.0">
			<name>Page margin-top</name>
			<definition>Unused space at the top of the document above the text.</definition>
			<description>"appearance"</description>
		</item>
		<item id="text-page2" type="java.lang.Float" scale="cm. / inch." version="1.0">
			<name>Page margin-right</name>
			<definition>Unused space at the right of the document above the text.</definition>
			<description>"appearance"</description>
		</item>
		<item id="text-page3" type="java.lang.Float" scale="cm. / inch." version="1.0">
			<name>Page margin-bottom</name>
			<definition>Unused space at the bottom of the document above the text.</definition>
			<description>"appearance"</description>
		</item>
		<item id="text-page4" type="java.lang.Float" scale="cm. / inch." version="1.0">
			<name>Page margin-left</name>
			<definition>Unused space at the left of the document above the text.</definition>
			<description>"appearance"</description>
		</item>
		<item id="text-page5" type="java.lang.Float" scale="cm. / inch." version="1.0">
			<name>Page height</name>
			<definition>Total height of the page.</definition>
			<description>"appearance"</description>
		</item>
		<item id="text-page6" type="java.lang.Float" scale="cm. / inch." version="1.0">
			<name>Page width</name>
			<definition>Total width of the page.</definition>
			<description>"appearance"</description>
		</item>
		<item id="text-page7" type="java.lang.Integer" scale="1..n" version="1.0">
			<name>Number of columns</name>
			<definition>Identifies the number of columns.</definition>
			<description>Count the number of columns on a page No columns means the number is 1. If there are several instances of "plain text" with different values, choose one to focus on. (for first version) "appearance"</description>
		</item>
		<item id="text-page8" type="java.lang.Float" scale="cm. / inch." version="1.0">
			<name>Columns spacing</name>
			<definition>Identifies the white space between two columns. </definition>
			<description>Define the unused space between two columns. If there are several values for this property, choose one to focus on. (for first version) "appearance"</description>
		</item>
		<item id="text-page9" type="java.lang.String" scale="proportional / absolute" version="1.0">
			<name>Letter / word spacing</name>
